# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=50)),
                ('zk_idc1', models.CharField(max_length=50)),
                ('zk_idc2', models.CharField(max_length=50)),
                ('namesrv', models.CharField(max_length=50)),
                ('broker_idc1', models.CharField(max_length=50)),
                ('broker_idc2', models.CharField(max_length=50)),
                ('cluster_name_idc1', models.CharField(max_length=50)),
                ('cluster_name_idc2', models.CharField(max_length=50)),
                ('idc1_code', models.CharField(max_length=10, verbose_name='idc1的编号')),
                ('idc2_code', models.CharField(max_length=10, verbose_name='idc2的编号')),
                ('rdfa_list', models.CharField(max_length=50, verbose_name='虚拟RDFA列表')),
                ('zk_root_path', models.CharField(max_length=50, verbose_name='zk的根地址')),
                ('orgId', models.CharField(max_length=10, verbose_name='法人号')),
                ('broadcast', models.CharField(max_length=20, verbose_name='广播地址')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('env', models.CharField(max_length=20)),
                ('service_id', models.CharField(max_length=20)),
                ('scene_id', models.CharField(max_length=20)),
                ('dfa', models.CharField(max_length=20)),
                ('zk_type', models.NullBooleanField()),
                ('giraffe_type', models.NullBooleanField()),
                ('create_time', models.DateTimeField(verbose_name='service create time')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('service_id', 'scene_id', 'dfa')]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceenv',
            unique_together=set([('env', 'service_id', 'scene_id', 'dfa')]),
        ),
    ]
