# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0003_environment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceEnv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_id', models.CharField(max_length=20)),
                ('scene_id', models.CharField(max_length=20)),
                ('dfa', models.CharField(max_length=20)),
                ('create_time', models.DateTimeField(verbose_name='service create time')),
            ],
        ),
        migrations.RemoveField(
            model_name='environment',
            name='service',
        ),
        migrations.AddField(
            model_name='serviceenv',
            name='env',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.Environment'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceenv',
            unique_together=set([('service_id', 'scene_id', 'dfa')]),
        ),
    ]
