# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0004_auto_20170730_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='operate_type',
            field=models.NullBooleanField(),
        ),
    ]
