# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0005_service_operate_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceenv',
            name='operate_type',
            field=models.NullBooleanField(),
        ),
    ]
