# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0006_serviceenv_operate_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='operate_type',
        ),
        migrations.AlterField(
            model_name='serviceenv',
            name='env',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='serviceenv',
            unique_together=set([('env', 'service_id', 'scene_id', 'dfa')]),
        ),
    ]
